const MOVIELIST = [
    {
      id: "1",
      title: "Game Night",
      year: "2018",
      genres: ["Action", "Comedy", "Crime"],
      ratings: [
        2,
        10,
        1,
        10,
        6,
        2,
        5,
        2,
        9,
        7,
        5,
        3,
        7,
        7,
        1,
        4,
        5,
        9,
        2,
        8,
        10,
        8,
        1,
        10,
        7,
        10,
        8,
        6,
        7,
        6
      ],
      poster:
        "MV5BMjQxMDE5NDg0NV5BMl5BanBnXkFtZTgwNTA5MDE2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "11",
      duration: "PT100M",
      releaseDate: "2018-02-28",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "A group of friends who meet regularly for game nights find themselves trying to solve a murder mystery.",
      actors: ["Rachel McAdams", "Jesse Plemons", "Jason Bateman"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQxMDE5NDg0NV5BMl5BanBnXkFtZTgwNTA5MDE2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "2",
      title: "Area X: Annihilation",
      year: "2018",
      genres: ["Adventure", "Drama", "Fantasy"],
      ratings: [
        2,
        6,
        2,
        3,
        9,
        5,
        3,
        10,
        6,
        7,
        3,
        1,
        6,
        6,
        1,
        7,
        8,
        8,
        7,
        2,
        3,
        2,
        10,
        4,
        9,
        8,
        2,
        2,
        6,
        3
      ],
      poster:
        "MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_SY500_CR0,0,320,500_AL_.jpg",
      contentRating: "R",
      duration: "",
      releaseDate: "2018-02-23",
      averageRating: 0,
      originalTitle: "Annihilation",
      storyline:
        "A biologist's husband disappears. She puts her name forward for an expedition into an environmental disaster zone, but does not find what she's expecting. The expedition team is made up of the biologist, an anthropologist, a psychologist, a surveyor, and a linguist.",
      actors: ["Tessa Thompson", "Jennifer Jason Leigh", "Natalie Portman"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_SY500_CR0,0,320,500_AL_.jpg"
    },
    {
      id: "3",
      title: "Hannah",
      year: "2017",
      genres: ["Drama"],
      ratings: [
        1,
        10,
        4,
        9,
        10,
        1,
        9,
        3,
        4,
        4,
        3,
        2,
        3,
        3,
        1,
        1,
        6,
        7,
        10,
        7,
        7,
        8,
        1,
        3,
        10,
        3,
        1,
        9,
        7,
        3
      ],
      poster:
        "MV5BNWJmMWIxMjQtZTk0Mi00YTE0LTkyNzAtYzQxYjcwYjE4ZDk2XkEyXkFqcGdeQXVyMTc4MzI2NQ@@._V1_SY500_SX350_AL_.jpg",
      contentRating: "",
      duration: "PT95M",
      releaseDate: "2018-01-24",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Intimate portrait of a woman drifting between reality and denial when she is left alone to grapple with the consequences of her husband's imprisonment.",
      actors: [
        "Charlotte Rampling",
        "Andr\u00e9 Wilms",
        "St\u00e9phanie Van Vyve"
      ],
      imdbRating: 6.5,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BNWJmMWIxMjQtZTk0Mi00YTE0LTkyNzAtYzQxYjcwYjE4ZDk2XkEyXkFqcGdeQXVyMTc4MzI2NQ@@._V1_SY500_SX350_AL_.jpg"
    },
    {
      id: "4",
      title: "The Lodgers",
      year: "2017",
      genres: ["Drama", "Horror", "Romance"],
      ratings: [
        7,
        5,
        1,
        5,
        4,
        10,
        2,
        7,
        6,
        4,
        10,
        5,
        1,
        5,
        3,
        6,
        9,
        1,
        3,
        4,
        9,
        1,
        7,
        6,
        7,
        5,
        7,
        2,
        10,
        10
      ],
      poster:
        "MV5BM2FhM2E1MTktMDYwZi00ODA1LWI0YTYtN2NjZjM3ODFjYmU5XkEyXkFqcGdeQXVyMjY1ODQ3NTA@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "R",
      duration: "PT92M",
      releaseDate: "2018-03-09",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "1920, rural Ireland. Anglo Irish twins Rachel and Edward share a strange existence in their crumbling family estate. Each night, the property becomes the domain of a sinister presence (The Lodgers) which enforces three rules upon the twins: they must be in bed by midnight; they may not permit an outsider past the threshold; if one attempts to escape, the life of the other is placed in jeopardy. When troubled war veteran Sean returns to the nearby village, he is immediately drawn to the mysterious Rachel, who in turn begins to break the rules set out by The Lodgers. The consequences pull Rachel into a deadly confrontation with her brother - and with the curse that haunts them.",
      actors: ["Charlotte Vega", "David Bradley", "Moe Dunford"],
      imdbRating: 5.8,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BM2FhM2E1MTktMDYwZi00ODA1LWI0YTYtN2NjZjM3ODFjYmU5XkEyXkFqcGdeQXVyMjY1ODQ3NTA@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "5",
      title: "Beast of Burden",
      year: "2018",
      genres: ["Action", "Crime", "Drama"],
      ratings: [
        9,
        5,
        5,
        5,
        5,
        6,
        10,
        6,
        6,
        9,
        6,
        2,
        2,
        9,
        4,
        6,
        6,
        9,
        7,
        8,
        7,
        10,
        8,
        5,
        3,
        1,
        1,
        5,
        6,
        2
      ],
      poster:
        "MV5BMjEyNTM3MDQ2NV5BMl5BanBnXkFtZTgwMDI5Nzk1NDM@._V1_SY500_CR0,0,336,500_AL_.jpg",
      contentRating: "R",
      duration: "",
      releaseDate: "2018-02",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Sean Haggerty only has an hour to deliver his illegal cargo. An hour to reassure a drug cartel, a hitman, and the DEA that nothing is wrong. An hour to make sure his wife survives. And he must do it all from the cockpit of his Cessna.",
      actors: ["Daniel Radcliffe", "Grace Gummer", "Pablo Schreiber"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyNTM3MDQ2NV5BMl5BanBnXkFtZTgwMDI5Nzk1NDM@._V1_SY500_CR0,0,336,500_AL_.jpg"
    },
    {
      id: "6",
      title: "The Chamber",
      year: "2016",
      genres: ["Horror", "Thriller"],
      ratings: [
        2,
        10,
        7,
        10,
        9,
        9,
        7,
        4,
        6,
        2,
        1,
        10,
        9,
        4,
        6,
        8,
        3,
        5,
        1,
        1,
        1,
        5,
        6,
        9,
        5,
        4,
        8,
        8,
        8,
        8
      ],
      poster:
        "MV5BNTVlODgwMjgtZGUzMy00ZTY1LWIyMDEtYTI2Y2JlYzVjZTNkXkEyXkFqcGdeQXVyNTg0MDM1MzY@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "",
      duration: "PT88M",
      releaseDate: "2017-03-10",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "A claustrophobic survival thriller set beneath the Yellow Sea off the coast of North Korea where the pilot of a small submersible craft and a three man Special Ops team on a secret recovery mission become trapped underwater in a fight for survival.",
      actors: ["Johannes Kuhnke", "Charlotte Salt", "James McArdle"],
      imdbRating: 4.4,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BNTVlODgwMjgtZGUzMy00ZTY1LWIyMDEtYTI2Y2JlYzVjZTNkXkEyXkFqcGdeQXVyNTg0MDM1MzY@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "7",
      title: "Survivors Guide to Prison",
      year: "2018",
      genres: ["Documentary"],
      ratings: [
        7,
        5,
        9,
        6,
        6,
        8,
        7,
        6,
        10,
        6,
        6,
        3,
        9,
        6,
        2,
        5,
        8,
        9,
        1,
        3,
        7,
        4,
        1,
        2,
        4,
        3,
        6,
        10,
        10,
        8
      ],
      poster:
        "MV5BNzhmNmI5MDMtZDEyOC00ODkyLTkwODItODQzODAzY2QyZjVlXkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_SY500_CR0,0,357,500_AL_.jpg",
      contentRating: "",
      duration: "PT102M",
      releaseDate: "2018-02-23",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Following the stories of Bruce Lisker and Reggie Cole who spent year after year in prison for murders they didn't commit - audiences get a harrowing look at how barbaric the US justice system is. The film ultimately asks how we can survive the prison model at all, and looks at better solutions for conflict resolution, harm reduction, crime and more. Hosted by filmmaker Matthew Cooke and guest hosting representatives from the massive range of Americans joining forces to change this broken system.                Written by\nanonymous",
      actors: ["Susan Sarandon", "Patricia Arquette", "Danny Trejo"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BNzhmNmI5MDMtZDEyOC00ODkyLTkwODItODQzODAzY2QyZjVlXkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_SY500_CR0,0,357,500_AL_.jpg"
    },
    {
      id: "8",
      title: "Red Sparrow",
      year: "2018",
      genres: ["Mystery", "Thriller"],
      ratings: [
        9,
        3,
        3,
        7,
        2,
        3,
        2,
        5,
        6,
        3,
        5,
        6,
        2,
        3,
        3,
        9,
        1,
        2,
        7,
        10,
        3,
        6,
        2,
        4,
        6,
        1,
        10,
        6,
        4,
        7
      ],
      poster:
        "MV5BMTA3MDkxOTc4NDdeQTJeQWpwZ15BbWU4MDAxNzgyNTQz._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "R",
      duration: "PT139M",
      releaseDate: "2018-03-02",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "A young Russian intelligence officer is assigned to seduce a first-tour CIA agent who handles the CIA's most sensitive penetration of Russian intelligence. The two young officers collide in a charged atmosphere of trade-craft, deception, and inevitably forbidden passion that threatens not just their lives but the lives of others as well.",
      actors: ["Jennifer Lawrence", "Joel Edgerton", "Charlotte Rampling"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA3MDkxOTc4NDdeQTJeQWpwZ15BbWU4MDAxNzgyNTQz._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "9",
      title: "Death Wish",
      year: "2018",
      genres: ["Action", "Crime", "Drama"],
      ratings: [
        2,
        9,
        5,
        9,
        7,
        7,
        4,
        5,
        5,
        6,
        5,
        3,
        7,
        10,
        4,
        8,
        2,
        9,
        7,
        10,
        2,
        10,
        3,
        1,
        4,
        6,
        4,
        6,
        7,
        3
      ],
      poster:
        "MV5BMTkzNjU3MjE0MF5BMl5BanBnXkFtZTgwNTIyNDk0NDM@._V1_SY400_SX270_AL_.jpg",
      contentRating: "R",
      duration: "PT108M",
      releaseDate: "2018-04-13",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Dr. Paul Kersey (Bruce Willis) is a surgeon who only sees the aftermath of his city's violence as it's rushed into his ER -until his wife (Elisabeth Shue) and college-age daughter (Camila Morrone) are viciously attacked in their suburban home. With the police overloaded with crimes, Paul, burning for revenge, hunts for his family's assailants to deliver justice. As the anonymous slayings of criminals grabs the media's attention, the city wonders if this deadly avenger is a guardian angel...or a grim reaper. Fury and fate collide in the intense action-thriller Death Wish.                Written by\nMGM",
      actors: ["Bruce Willis", "Vincent D'Onofrio", "Elisabeth Shue"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkzNjU3MjE0MF5BMl5BanBnXkFtZTgwNTIyNDk0NDM@._V1_SY400_SX270_AL_.jpg"
    },
    {
      id: "10",
      title: "Foxtrot",
      year: "2017",
      genres: ["Drama"],
      ratings: [
        9,
        6,
        5,
        8,
        3,
        9,
        10,
        2,
        8,
        1,
        9,
        4,
        1,
        3,
        2,
        9,
        2,
        4,
        2,
        7,
        3,
        2,
        1,
        10,
        6,
        6,
        1,
        3,
        10,
        9
      ],
      poster:
        "MV5BOGUyZTJhZWEtNGIwZi00YjUwLTljMGMtNjliMzM1NDMxYjJmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY500_CR0,0,353,500_AL_.jpg",
      contentRating: "R",
      duration: "PT108M",
      releaseDate: "2017-09-21",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "A troubled family face the facts when something goes terribly wrong at their son's desolate military post.",
      actors: ["Lior Ashkenazi", "Sarah Adler", "Yonaton Shiray"],
      imdbRating: 7.4,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BOGUyZTJhZWEtNGIwZi00YjUwLTljMGMtNjliMzM1NDMxYjJmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY500_CR0,0,353,500_AL_.jpg"
    },
    {
      id: "11",
      title: "They Remain",
      year: "2018",
      genres: ["Thriller"],
      ratings: [
        3,
        6,
        9,
        3,
        9,
        6,
        4,
        1,
        10,
        1,
        1,
        9,
        7,
        7,
        6,
        8,
        6,
        6,
        6,
        8,
        8,
        10,
        7,
        2,
        9,
        10,
        8,
        6,
        9,
        4
      ],
      poster:
        "MV5BMjI0NTEzMTk1OV5BMl5BanBnXkFtZTgwNTMwNDY3NDM@._V1_SY500_CR0,0,349,500_AL_.jpg",
      contentRating: "",
      duration: "",
      releaseDate: "2018-01-28",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Two scientists who share a romantic history are tasked with investigating unnatural animal behaviour on the site of a Manson Family-style cult's compound.",
      actors: ["William Jackson Harper", "Rebecca Henderson"],
      imdbRating: 7.6,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjI0NTEzMTk1OV5BMl5BanBnXkFtZTgwNTMwNDY3NDM@._V1_SY500_CR0,0,349,500_AL_.jpg"
    },
    {
      id: "12",
      title: "Submission",
      year: "2017",
      genres: ["Drama"],
      ratings: [
        5,
        3,
        9,
        8,
        9,
        1,
        7,
        8,
        6,
        5,
        3,
        1,
        8,
        4,
        7,
        2,
        9,
        9,
        2,
        2,
        4,
        5,
        9,
        10,
        8,
        5,
        7,
        6,
        4,
        5
      ],
      poster:
        "MV5BMjQ4NDkwMzM4OF5BMl5BanBnXkFtZTgwNzE3MzI3NDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "",
      duration: "",
      releaseDate: "2017-10-13",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "A cynical college professor takes a keen interest in a talented young writing student.",
      actors: ["Stanley Tucci", "Addison Timlin", "Kyra Sedgwick"],
      imdbRating: 6.1,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQ4NDkwMzM4OF5BMl5BanBnXkFtZTgwNzE3MzI3NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "13",
      title: "Souvenir",
      year: "2016",
      genres: ["Drama", "Music", "Romance"],
      ratings: [
        2,
        3,
        5,
        5,
        8,
        6,
        6,
        2,
        10,
        5,
        5,
        1,
        5,
        8,
        9,
        3,
        5,
        10,
        4,
        10,
        2,
        3,
        7,
        5,
        6,
        4,
        5,
        3,
        10,
        2
      ],
      poster:
        "MV5BZmJkZjVhNGUtOTg4MC00YzAwLTg4ZjEtZjAxYmVlNTlkOTgyXkEyXkFqcGdeQXVyNTQwMDA5NTg@._V1_SY500_CR0,0,333,500_AL_.jpg",
      contentRating: "Btl",
      duration: "PT90M",
      releaseDate: "2017-05-19",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Because of the stupid life in a p\u00e2t\u00e9-factory, former singer Laura falls in love with a colleague, a much younger boy and boxer, and after a small performance, a reenactment of her singing character, she tries to reenter the national song contest.                Written by\nimperiumclassicum",
      actors: ["Isabelle Huppert", "K\u00e9vin Aza\u00efs", "Johan Leysen"],
      imdbRating: 6.1,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BZmJkZjVhNGUtOTg4MC00YzAwLTg4ZjEtZjAxYmVlNTlkOTgyXkEyXkFqcGdeQXVyNTQwMDA5NTg@._V1_SY500_CR0,0,333,500_AL_.jpg"
    },
    {
      id: "14",
      title: "Dance Academy: The Movie",
      year: "2017",
      genres: ["Drama"],
      ratings: [
        10,
        1,
        8,
        7,
        4,
        10,
        1,
        2,
        7,
        2,
        7,
        3,
        10,
        2,
        5,
        4,
        6,
        10,
        10,
        10,
        6,
        2,
        6,
        10,
        2,
        3,
        1,
        6,
        8,
        7
      ],
      poster:
        "MV5BYjg2MzMwYmYtNjkwMS00N2VmLWI2MDMtMDA2ZjZiMDBkZDk1L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTg3ODAyOTY@._V1_SY500_SX400_AL_.jpg",
      contentRating: "",
      duration: "PT101M",
      releaseDate: "2017-04-06",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "This 2017 movie follows the original dance academy TV show and tracks where the characters are in their lives now.",
      actors: ["Alex Acosta", "Alicia Banit", "Chris Bartlett"],
      imdbRating: 7.0,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BYjg2MzMwYmYtNjkwMS00N2VmLWI2MDMtMDA2ZjZiMDBkZDk1L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTg3ODAyOTY@._V1_SY500_SX400_AL_.jpg"
    },
    {
      id: "15",
      title: "Ett veck i tiden",
      year: "2018",
      genres: ["Adventure", "Family", "Fantasy"],
      ratings: [
        1,
        1,
        1,
        1,
        1,
        1,
        9,
        8,
        8,
        8,
        8,
        3,
        4,
        4,
        6,
        4,
        8,
        6,
        2,
        5,
        3,
        8,
        10,
        3,
        8,
        2,
        1,
        6,
        10,
        7
      ],
      poster:
        "MV5BMjMxNjQ5MTI3MV5BMl5BanBnXkFtZTgwMjQ2MTAyNDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "PG",
      duration: "",
      releaseDate: "2018-04-06",
      averageRating: 0,
      originalTitle: "A Wrinkle in Time",
      storyline:
        "Following the discovery of a new form of space travel as well as Meg's father's disappearance, she, her brother, and her friend must join three magical beings - Mrs. Whatsit, Mrs. Who, and Mrs. Which - to travel across the universe to rescue him from a terrible evil.",
      actors: ["Gugu Mbatha-Raw", "Reese Witherspoon", "Chris Pine"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMxNjQ5MTI3MV5BMl5BanBnXkFtZTgwMjQ2MTAyNDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "16",
      title: "The Strangers: Prey at Night",
      year: "2018",
      genres: ["Horror"],
      ratings: [
        9,
        7,
        7,
        4,
        6,
        4,
        2,
        7,
        10,
        5,
        7,
        8,
        6,
        1,
        8,
        2,
        5,
        6,
        1,
        6,
        5,
        4,
        1,
        6,
        10,
        2,
        3,
        6,
        6,
        3
      ],
      poster:
        "MV5BMTY1OTIwODgzMV5BMl5BanBnXkFtZTgwMzUyMDgzNDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "R",
      duration: "",
      releaseDate: "2018-03-09",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "A family's road trip takes a dangerous turn when they arrive at a secluded mobile home park to stay with some relatives and find it mysteriously deserted. Under the cover of darkness, three masked psychopaths pay them a visit to test the family's every limit as they struggle to survive.                Written by\nAviron Pictures",
      actors: ["Christina Hendricks", "Bailee Madison", "Martin Henderson"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY1OTIwODgzMV5BMl5BanBnXkFtZTgwMzUyMDgzNDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "17",
      title: "The Hurricane Heist",
      year: "2018",
      genres: ["Action", "Thriller"],
      ratings: [
        9,
        6,
        1,
        5,
        10,
        6,
        9,
        8,
        7,
        2,
        3,
        10,
        4,
        9,
        7,
        7,
        6,
        3,
        7,
        8,
        9,
        1,
        1,
        9,
        2,
        7,
        1,
        4,
        1,
        7
      ],
      poster:
        "MV5BMzg3Y2MyNjgtMzk4ZS00OTU3LWEwZmMtN2Y0NTdlZjU0NGFiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "PG-13",
      duration: "",
      releaseDate: "2018-03-23",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Thieves attempt a massive heist against the U.S. Treasury as a Category 5 hurricane approaches one of its Mint facilities.",
      actors: ["Toby Kebbell", "Maggie Grace", "Ryan Kwanten"],
      imdbRating: 6.8,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMzg3Y2MyNjgtMzk4ZS00OTU3LWEwZmMtN2Y0NTdlZjU0NGFiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "18",
      title: "Gringo",
      year: "2018",
      genres: ["Action", "Comedy", "Drama"],
      ratings: [
        7,
        6,
        5,
        2,
        10,
        4,
        10,
        1,
        7,
        4,
        6,
        8,
        3,
        4,
        7,
        9,
        3,
        5,
        7,
        6,
        2,
        6,
        8,
        10,
        2,
        4,
        6,
        4,
        9,
        10
      ],
      poster:
        "MV5BMjAyMTk2MTQ3Ml5BMl5BanBnXkFtZTgwNDQ2ODE0NDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "R",
      duration: "PT110M",
      releaseDate: "2018-03-09",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "An exhilarating mix of dark comedy, white-knuckle action and dramatic intrigue, Gringo joyrides into Mexico, where mild-mannered businessman Harold Soyinka (David Oyelowo) finds himself at the mercy of his back-stabbing business colleagues back home, local drug lords and a morally conflicted black-ops mercenary. Crossing the line from law-abiding citizen to wanted criminal, Harold battles to survive his increasingly dangerous situation in ways that raise the question: Is he out of his depth - or two steps ahead?                Written by\nAmazon Studios",
      actors: ["David Oyelowo", "Charlize Theron", "Joel Edgerton"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAyMTk2MTQ3Ml5BMl5BanBnXkFtZTgwNDQ2ODE0NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "19",
      title: "Thoroughbreds",
      year: "2017",
      genres: ["Drama", "Thriller"],
      ratings: [
        7,
        9,
        2,
        9,
        2,
        10,
        5,
        5,
        8,
        3,
        2,
        6,
        6,
        2,
        6,
        1,
        6,
        6,
        2,
        7,
        1,
        6,
        10,
        10,
        10,
        8,
        9,
        4,
        7,
        5
      ],
      poster:
        "MV5BMTk4MzQ1NDY2OF5BMl5BanBnXkFtZTgwNjA4Nzc4MzI@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "",
      duration: "PT92M",
      releaseDate: "2018-03-09",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Two upper-class teenage girls in suburban Connecticut rekindle their unlikely friendship after years of growing apart. Together, they hatch a plan to solve both of their problems-no matter what the cost.",
      actors: ["Anya Taylor-Joy", "Olivia Cooke", "Paul Sparks"],
      imdbRating: 7.0,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk4MzQ1NDY2OF5BMl5BanBnXkFtZTgwNjA4Nzc4MzI@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "20",
      title: "En sista semester",
      year: "2017",
      genres: ["Adventure", "Comedy", "Drama"],
      ratings: [
        5,
        7,
        6,
        8,
        1,
        1,
        3,
        7,
        6,
        1,
        10,
        1,
        9,
        1,
        9,
        4,
        1,
        5,
        8,
        10,
        7,
        9,
        8,
        4,
        7,
        7,
        10,
        7,
        1,
        2
      ],
      poster:
        "MV5BMTg1NTg2MzcyNF5BMl5BanBnXkFtZTgwNjMwMDIzNDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "7",
      duration: "PT112M",
      releaseDate: "2018-03-16",
      averageRating: 0,
      originalTitle: "The Leisure Seeker",
      storyline:
        "A runaway couple go on an unforgettable journey in the faithful old RV they call The Leisure Seeker, traveling from Boston to The Ernest Hemingway Home in Key West. They recapture their passion for life and their love for each other on a road trip that provides revelation and surprise right up to the very end.",
      actors: ["Helen Mirren", "Donald Sutherland", "Janel Moloney"],
      imdbRating: 6.5,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg1NTg2MzcyNF5BMl5BanBnXkFtZTgwNjMwMDIzNDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "21",
      title: "Leaning Into the Wind: Andy Goldsworthy",
      year: "2017",
      genres: ["Documentary"],
      ratings: [
        9,
        9,
        10,
        10,
        6,
        10,
        3,
        2,
        2,
        7,
        1,
        10,
        10,
        5,
        6,
        9,
        8,
        4,
        6,
        6,
        9,
        2,
        6,
        2,
        5,
        3,
        5,
        9,
        2,
        1
      ],
      poster:
        "MV5BYWRjMTZhN2ItZDE1MC00NWQyLThkZTUtMTRjMGZhODE0NTQxXkEyXkFqcGdeQXVyMjA1NzQwNjM@._V1_SY190_SX318_AL_.jpg",
      contentRating: "PG",
      duration: "PT93M",
      releaseDate: "2017-12-14",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Sixteen years after the release of the ground-breaking film Rivers and Tides - Andy Goldsworthy Working with Time director Thomas Riedelsheimer has returned to work with the artist. Leaning into the Wind - Andy Goldsworthy follows Andy on his exploration of the layers of his world and the impact of the years on himself and his art. As Goldsworthy introduces his own body into the work it becomes at the same time even more fragile and personal and also sterner and tougher, incorporating massive machinery and crews on his bigger projects. Riedelsheimer's exquisite film illuminates Goldsworthy's mind as it reveals his art.                Written by\nLeslie Hills",
      actors: ["Andy Goldsworthy", "Holly Goldsworthy"],
      imdbRating: 7.3,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BYWRjMTZhN2ItZDE1MC00NWQyLThkZTUtMTRjMGZhODE0NTQxXkEyXkFqcGdeQXVyMjA1NzQwNjM@._V1_SY190_SX318_AL_.jpg"
    },
    {
      id: "22",
      title: "Tomb Raider",
      year: "2018",
      genres: ["Action", "Adventure"],
      ratings: [
        5,
        3,
        6,
        10,
        3,
        2,
        5,
        7,
        1,
        8,
        8,
        10,
        4,
        1,
        2,
        4,
        5,
        2,
        9,
        8,
        6,
        7,
        8,
        8,
        1,
        8,
        3,
        3,
        3,
        3
      ],
      poster:
        "MV5BOTY4NDcyZGQtYmVlNy00ODgwLTljYTMtYzQ2OTE3NDhjODMwXkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "PG-13",
      duration: "",
      releaseDate: "2018-03-16",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Lara Croft is the fiercely independent daughter of an eccentric adventurer who vanished when she was scarcely a teen. Now a young woman of 21 without any real focus or purpose, Lara navigates the chaotic streets of trendy East London as a bike courier, barely making the rent, and takes college courses, rarely making it to class. Determined to forge her own path, she refuses to take the reins of her father's global empire just as staunchly as she rejects the idea that he's truly gone. Advised to face the facts and move forward after seven years without him, even Lara can't understand what drives her to finally solve the puzzle of his mysterious death. Going explicitly against his final wishes, she leaves everything she knows behind in search of her dad's last-known destination: a fabled tomb on a mythical island that might be somewhere off the coast of Japan. But her mission will not be an easy one; just reaching the island will be extremely treacherous. Suddenly, the stakes couldn't ...                Written by\nWarner Bros. Pictures",
      actors: ["Alicia Vikander", "Hannah John-Kamen", "Walton Goggins"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BOTY4NDcyZGQtYmVlNy00ODgwLTljYTMtYzQ2OTE3NDhjODMwXkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "23",
      title: "Love, Simon",
      year: "2018",
      genres: ["Comedy", "Drama", "Romance"],
      ratings: [
        8,
        10,
        10,
        9,
        4,
        3,
        2,
        8,
        2,
        5,
        2,
        9,
        7,
        7,
        1,
        6,
        1,
        6,
        10,
        10,
        7,
        2,
        3,
        10,
        9,
        4,
        7,
        10,
        8,
        10
      ],
      poster:
        "MV5BZTVkOWJkOTYtM2FlZS00YTBlLWE2YTYtODEyZWJjMTZkM2IzXkEyXkFqcGdeQXVyMTQ4NzkzOTA@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "PG-13",
      duration: "PT109M",
      releaseDate: "2018-06-15",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Everyone deserves a great love story. But for Simon it's complicated: no-one knows he's gay and he doesn't know who the anonymous classmate is that he's fallen for online. Resolving both issues proves hilarious, scary and life-changing.",
      actors: ["Nick Robinson", "Josh Duhamel", "Jennifer Garner"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BZTVkOWJkOTYtM2FlZS00YTBlLWE2YTYtODEyZWJjMTZkM2IzXkEyXkFqcGdeQXVyMTQ4NzkzOTA@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "24",
      title: "Entebbe",
      year: "2018",
      genres: ["Crime", "Drama", "Thriller"],
      ratings: [
        6,
        4,
        9,
        10,
        4,
        7,
        3,
        7,
        1,
        1,
        3,
        7,
        8,
        6,
        2,
        5,
        10,
        6,
        4,
        4,
        5,
        4,
        5,
        7,
        1,
        2,
        2,
        3,
        10,
        8
      ],
      poster:
        "MV5BMjAwNDMzNzg0Nl5BMl5BanBnXkFtZTgwOTkxNjY2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "PG-13",
      duration: "PT106M",
      releaseDate: "2018-03-16",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "In July 1976, an Air France flight from Tel-Aviv to Paris via Athens was hijacked and forced to land in Entebbe, Uganda. The Jewish passengers were separated and held hostage in demand to release many terrorists held in Israeli prisons. After much debate, the Israeli government sent an elite commando unit to raid the airfield and release the hostages.",
      actors: ["Daniel Br\u00fchl", "Rosamund Pike", "Eddie Marsan"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAwNDMzNzg0Nl5BMl5BanBnXkFtZTgwOTkxNjY2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "25",
      title: "Flower",
      year: "2017",
      genres: ["Comedy", "Drama"],
      ratings: [
        3,
        7,
        8,
        3,
        7,
        2,
        5,
        4,
        7,
        2,
        2,
        4,
        4,
        9,
        9,
        4,
        6,
        7,
        10,
        4,
        7,
        9,
        2,
        8,
        5,
        3,
        10,
        6,
        6,
        8
      ],
      poster:
        "MV5BYzViOTBmMGUtODBlMi00YzYzLThiM2MtOGFlMzZkNWU4NDRjXkEyXkFqcGdeQXVyODE0MDY3NzY@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "R",
      duration: "PT90M",
      releaseDate: "2018-03-16",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "A sexually curious teen forms an unorthodox kinship with her mentally unstable stepbrother.",
      actors: ["Zoey Deutch", "Kathryn Hahn", "Adam Scott"],
      imdbRating: 6.7,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BYzViOTBmMGUtODBlMi00YzYzLThiM2MtOGFlMzZkNWU4NDRjXkEyXkFqcGdeQXVyODE0MDY3NzY@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "26",
      title: "Huntsville",
      year: "2017",
      genres: ["Drama", "Thriller"],
      ratings: [
        3,
        7,
        1,
        1,
        10,
        10,
        6,
        5,
        8,
        6,
        5,
        5,
        1,
        6,
        5,
        2,
        7,
        10,
        5,
        10,
        10,
        9,
        10,
        5,
        1,
        9,
        1,
        10,
        9,
        7
      ],
      poster:
        "MV5BYWRjMzNmNmMtNGM1NC00OGU5LWJhNmMtNmUzNDMwZjBiOGNhXkEyXkFqcGdeQXVyMjA1MDcxMw@@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "",
      duration: "PT100M",
      releaseDate: "2018-03-16",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Hank, a solitary man living a dull existence in the sleepy, Southern town raises eyebrows when he develops a questionable relationship with Josie, a recently transplanted high school student.",
      actors: ["Sophie Turner", "Dylan McDermott", "Jack Kilmer"],
      imdbRating: 7.6,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BYWRjMzNmNmMtNGM1NC00OGU5LWJhNmMtNmUzNDMwZjBiOGNhXkEyXkFqcGdeQXVyMjA1MDcxMw@@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "27",
      title: "I Can Only Imagine",
      year: "2018",
      genres: ["Drama", "Family"],
      ratings: [
        6,
        9,
        4,
        9,
        3,
        4,
        10,
        3,
        2,
        9,
        9,
        9,
        2,
        3,
        5,
        9,
        8,
        9,
        1,
        5,
        8,
        10,
        1,
        5,
        2,
        8,
        5,
        3,
        5,
        8
      ],
      poster:
        "MV5BMTRjNDc5NTAtZGJlYS00NTg4LTk2NTEtNGUwY2NiZWM3YTY2XkEyXkFqcGdeQXVyNTQ3MjE4NTU@._V1_SY456_SX295_AL_.jpg",
      contentRating: "PG",
      duration: "PT110M",
      releaseDate: "2018-03-16",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "The inspiring and unknown true story behind MercyMe's beloved, chart topping song that brings ultimate hope to so many is a gripping reminder of the power of true forgiveness.",
      actors: ["J. Michael Finley", "Brody Rose", "Dennis Quaid"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTRjNDc5NTAtZGJlYS00NTg4LTk2NTEtNGUwY2NiZWM3YTY2XkEyXkFqcGdeQXVyNTQ3MjE4NTU@._V1_SY456_SX295_AL_.jpg"
    },
    {
      id: "28",
      title: "Journey's End",
      year: "2017",
      genres: ["Drama", "War"],
      ratings: [
        4,
        8,
        2,
        5,
        8,
        5,
        4,
        1,
        7,
        4,
        4,
        3,
        6,
        7,
        8,
        6,
        5,
        7,
        8,
        8,
        1,
        9,
        4,
        5,
        1,
        1,
        10,
        2,
        10,
        1
      ],
      poster:
        "MV5BOTAyZDBiYjktMTdlZi00MGQ5LWE5NmItYjI3YWMwN2I0NjYxXkEyXkFqcGdeQXVyNjUzODM0ODI@._V1_SY400_CR0,0,272,400_AL_.jpg",
      contentRating: "R",
      duration: "PT107M",
      releaseDate: "2018-02-02",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Set in a dugout in Aisne in 1918, it is the story of a group of British officers, led by the mentally disintegrating young officer Stanhope, as they await their fate.",
      actors: ["Paul Bettany", "Sam Claflin", "Asa Butterfield"],
      imdbRating: 7.2,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BOTAyZDBiYjktMTdlZi00MGQ5LWE5NmItYjI3YWMwN2I0NjYxXkEyXkFqcGdeQXVyNjUzODM0ODI@._V1_SY400_CR0,0,272,400_AL_.jpg"
    },
    {
      id: "29",
      title: "Ramen Heads",
      year: "2017",
      genres: ["Documentary"],
      ratings: [
        7,
        4,
        10,
        6,
        1,
        8,
        9,
        8,
        1,
        3,
        5,
        2,
        7,
        6,
        6,
        1,
        1,
        6,
        4,
        8,
        10,
        8,
        6,
        7,
        5,
        6,
        6,
        3,
        8,
        7
      ],
      poster:
        "MV5BMTAzNDk5NzQyNDReQTJeQWpwZ15BbWU4MDYyODA2NzQz._V1_SY500_CR0,0,333,500_AL_.jpg",
      contentRating: "",
      duration: "PT93M",
      releaseDate: "2018-01-27",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "In 'Ramen Heads,' Osamu Tomita, Japan's reigning king of ramen, takes us deep into his world, revealing every single step of his obsessive approach to creating the perfect soup and noodles, and his relentless search for the highest-quality ingredients. In addition to Tomita's story, the film also profiles five other notable ramen shops, each with its own philosophy and flavour, which exemplify various different aspects the ramen world. Mixing in a brief rundown of ramen's historical roots, the film gives viewers an in-depth look at the culture surrounding this unique and beguiling dish. This is a documentary record of 15 months in the lives of Japan's top ramen masters and their legions of devoted fans.",
      actors: ["Sh\u00f4ta Iida", "Kumiko Ishida", "Katsuya Kobayashi"],
      imdbRating: 7.2,
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTAzNDk5NzQyNDReQTJeQWpwZ15BbWU4MDYyODA2NzQz._V1_SY500_CR0,0,333,500_AL_.jpg"
    },
    {
      id: "30",
      title: "Pacific Rim Uprising",
      year: "2018",
      genres: ["Action", "Adventure", "Sci-Fi"],
      ratings: [
        7,
        3,
        6,
        6,
        7,
        8,
        6,
        10,
        4,
        7,
        10,
        1,
        4,
        4,
        1,
        1,
        1,
        6,
        4,
        9,
        8,
        6,
        5,
        4,
        10,
        6,
        8,
        1,
        3,
        3
      ],
      poster:
        "MV5BMjExMjM3MzM4NV5BMl5BanBnXkFtZTgwNjIyMzQ2NDM@._V1_SY500_CR0,0,315,500_AL_.jpg",
      contentRating: "PG-13",
      duration: "",
      releaseDate: "2018-03-23",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Jake Pentecost, son of Stacker Pentecost, reunites with Mako Mori to lead a new generation of Jaeger pilots, including rival Lambert and 15-year-old hacker Amara, against a new Kaiju threat.",
      actors: ["Scott Eastwood", "Adria Arjona", "Tian Jing"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjExMjM3MzM4NV5BMl5BanBnXkFtZTgwNjIyMzQ2NDM@._V1_SY500_CR0,0,315,500_AL_.jpg"
    },
    {
      id: "31",
      title: "Isle of Dogs",
      year: "2018",
      genres: ["Animation", "Adventure", "Comedy"],
      ratings: [
        8,
        9,
        3,
        1,
        10,
        7,
        4,
        1,
        10,
        10,
        1,
        6,
        7,
        4,
        2,
        10,
        9,
        10,
        1,
        8,
        1,
        2,
        4,
        1,
        9,
        4,
        4,
        6,
        10,
        8
      ],
      poster:
        "MV5BMTYyOTUwNjAxM15BMl5BanBnXkFtZTgwODcyMzE0NDM@._V1_SX265_CR0,0,265,420_AL_.jpg",
      contentRating: "PG-13",
      duration: "",
      releaseDate: "2018-05-04",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Set in Japan, Isle of Dogs follows a boy's odyssey in search of his dog.",
      actors: ["Bryan Cranston", "Koyu Rankin", "Edward Norton"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYyOTUwNjAxM15BMl5BanBnXkFtZTgwODcyMzE0NDM@._V1_SX265_CR0,0,265,420_AL_.jpg"
    },
    {
      id: "32",
      title: "Unsane",
      year: "2018",
      genres: ["Horror", "Thriller"],
      ratings: [
        2,
        1,
        10,
        10,
        3,
        7,
        3,
        3,
        10,
        1,
        5,
        9,
        9,
        8,
        8,
        4,
        5,
        7,
        8,
        9,
        6,
        4,
        5,
        4,
        2,
        1,
        6,
        1,
        9,
        1
      ],
      poster:
        "MV5BNTYzMDYzMzA1MV5BMl5BanBnXkFtZTgwODUzODg2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "R",
      duration: "",
      releaseDate: "2018-06-20",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "A young woman is involuntarily committed to a mental institution, where she is confronted by her greatest fear--but is it real or a product of her delusion?",
      actors: ["Claire Foy", "Juno Temple", "Aimee Mullins"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BNTYzMDYzMzA1MV5BMl5BanBnXkFtZTgwODUzODg2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      id: "33",
      title: "Sherlock Gnomes",
      year: "2018",
      genres: ["Animation", "Adventure", "Comedy"],
      ratings: [
        10,
        1,
        5,
        4,
        3,
        5,
        8,
        6,
        1,
        4,
        10,
        6,
        10,
        1,
        9,
        4,
        7,
        6,
        9,
        7,
        5,
        1,
        6,
        9,
        6,
        8,
        6,
        1,
        4,
        5
      ],
      poster:
        "MV5BMTk4NzU3NzU2NV5BMl5BanBnXkFtZTgwNDc4NTI3NDM@._V1_SY500_CR0,0,320,500_AL_.jpg",
      contentRating: "",
      duration: "",
      releaseDate: "2018-03-23",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "Garden gnomes, Gnomeo & Juliet, recruit renowned detective Sherlock Gnomes to investigate the mysterious disappearance of other garden ornaments.",
      actors: ["Emily Blunt", "Johnny Depp", "James McAvoy"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk4NzU3NzU2NV5BMl5BanBnXkFtZTgwNDc4NTI3NDM@._V1_SY500_CR0,0,320,500_AL_.jpg"
    },
    {
      id: "34",
      title: "Paul, Apostle of Christ",
      year: "2018",
      genres: ["Drama"],
      ratings: [
        8,
        1,
        8,
        1,
        9,
        10,
        6,
        4,
        8,
        1,
        10,
        4,
        8,
        6,
        8,
        5,
        8,
        9,
        2,
        9,
        7,
        5,
        10,
        7,
        5,
        2,
        2,
        4,
        2,
        9
      ],
      poster:
        "MV5BMWRkYTQ4NzctMDAwYS00NmE3LWI5NzUtMTMzNTQ0MDgwOWI1XkEyXkFqcGdeQXVyODQyOTY2OTA@._V1_SY500_CR0,0,337,500_AL_.jpg",
      contentRating: "PG-13",
      duration: "",
      releaseDate: "2018-03-28",
      averageRating: 0,
      originalTitle: "",
      storyline:
        "PAUL, APOSTLE OF CHRIST is the story of two men. Luke, as a friend and physician, risks his life when he ventures into the city of Rome to visit Paul, who is held captive in Nero's darkest, bleakest prison cell. . But Nero is determined to rid Rome of Christians, and does not flinch from executing them in the grisliest ways possible. Before Paul's death sentence can be enacted, Luke resolves to write another book, one that details the beginnings of \"The Way\" and the birth of what will come to be known as the church. Bound in chains, Paul's struggle is internal. He has survived so much-floggings, shipwreck, starvation, stoning, hunger and thirst, cold and exposure-yet as he waits for his appointment with death, he is haunted by the shadows of his past misdeeds. Alone in the dark, he wonders if he has been forgotten . . . and if he has the strength to finish well. Two men struggle against a determined emperor and the frailties of the human spirit in order to live out the Gospel of Jesus...",
      actors: ["James Faulkner", "Jim Caviezel", "Joanne Whalley"],
      imdbRating: "",
      posterurl:
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMWRkYTQ4NzctMDAwYS00NmE3LWI5NzUtMTMzNTQ0MDgwOWI1XkEyXkFqcGdeQXVyODQyOTY2OTA@._V1_SY500_CR0,0,337,500_AL_.jpg"
    }
];

export function getMoviesData(count = 50) {
  if (!count || count <= 0) {
    count = 50;
  }

  const movies = [];
  for (let i = 0; i < count; i++) {
    movies.push(MOVIELIST[i]);
  }

  return movies;
}

